### ISSUE TITLE
无法进入安装界面

### ISSUE THREAD

**Issue by mogudada** [threewater2/hackintosh#1]
10.15.7 是黑苹果小兵
![image](https://user-images.githubusercontent.com/34201576/102328359-ee0d0200-3fc1-11eb-83a3-9476a6905ca0.png)
![image](https://user-images.githubusercontent.com/34201576/102328376-f6653d00-3fc1-11eb-90f4-d7940141854b.png)

**Comment by PurestAsh** [comment]
> 10.15.7 是黑苹果小兵
> ![image](https://user-images.githubusercontent.com/34201576/102328359-ee0d0200-3fc1-11eb-83a3-9476a6905ca0.png)
> ![image](https://user-images.githubusercontent.com/34201576/102328376-f6653d00-3fc1-11eb-90f4-d7940141854b.png)

cfg锁解了没
