### ISSUE TITLE
独显需要屏蔽吗

### ISSUE THREAD

**Issue by Rincaron** [threewater2/hackintosh#2]
我开机进苹果logo，进度条到一半的时候苹果logo变成禁止🚫标志，是独显的问题吗？要怎么屏蔽？

**Comment by PurestAsh** [comment]
你先试试debug版,然后发一下代码截图,看看卡在哪里

**Comment by Rincaron** [comment]
> 你先试试debug版,然后发一下代码截图,看看卡在哪里

![image](https://user-images.githubusercontent.com/72061002/116413518-460a1e00-a86a-11eb-8858-6c4ee6961740.jpeg)

现在一直在循环打印最后一行

**Comment by PurestAsh** [comment]
再等等

**Comment by Rincaron** [comment]
> 再等等

现在是这个，过一会会清屏重新打印“message” ![image](https://user-images.githubusercontent.com/72061002/116414927-81591c80-a86b-11eb-9105-2dd0b6dae5a6.jpeg)

**Comment by PurestAsh** [comment]
BIOS中的DVMT Pre-Allocated 是256M吗

**Comment by Rincaron** [comment]
> BIOS中的DVMT Pre-Allocated 是256M吗
> 
> 
> 
> 
> 
> 
是256M，这笔记本我换过内存条，这个有影响吗

**Comment by PurestAsh** [comment]
CFG锁解了吗?您的电脑型号是zx50v(D面)吗?
我这里有一个无蓝牙版本的,你要不要试试
https://cloud.threewater.xyz/

**Comment by PurestAsh** [comment]
把Luanch CSM设为启用试试
或者插到usb2.0的口,或者使用usb2.0的u盘试试

**Comment by Rincaron** [comment]
> CFG锁解了吗?您的电脑型号是zx50v(D面)吗?
> 
> 我这里有一个无蓝牙版本的,你要不要试试
> 
> https://cloud.threewater.xyz/

无蓝牙版本运行结果
![image](https://user-images.githubusercontent.com/72061002/116421757-b7010400-a871-11eb-984a-0db76161c9d9.jpeg)

CFGLock.efi打开
![image](https://user-images.githubusercontent.com/72061002/116421886-d435d280-a871-11eb-902f-56607b2f3a54.jpeg)

笔记本型号
![image](https://user-images.githubusercontent.com/72061002/116421966-e3b51b80-a871-11eb-8ada-2bbe846900b9.jpeg)

我不清楚CFG怎么解锁😓

**Comment by PurestAsh** [comment]
![QQ图片20210428224219](https://user-images.githubusercontent.com/23291517/116423160-01cf4b80-a873-11eb-9061-09fea3cfc985.jpg)

我的CFG解锁是这样的,你的CFG看意思好像解不了.

**Comment by Rincaron** [comment]
不知道和BIOS版本有没有关系，可以提供下您机器的BIOS版本和CFGLock.efi文件吗，另外我发现我的U盘是3.0的，我找个2.0的再试一下 @threewater2

**Comment by PurestAsh** [comment]
CFGLock我的和你一样的
BIOS版本要求304
我没有3.0的U盘,或者换个口试试
我这里有一个旧SATA支持的OC,你要不要试试?
https://cloud.threewater.xyz/下面的OC2.0.zip

**Comment by Rincaron** [comment]
好的，等晚上我再试下

**Comment by Rincaron** [comment]
在安装了，感谢大佬！之前失败原因是bios没有升级😅

**Comment by PurestAsh** [comment]
你好,我不是大佬,成功了能给张截图吗?

**Comment by Rincaron** [comment]
> 你好,我不是大佬,成功了能给张截图吗?

嗯，还在安装，等下安装好了截图

**Comment by PurestAsh** [comment]
好的,谢谢😀

**Comment by PurestAsh** [comment]
你用的是哪个版本?是cloud.threwwater.xyz下面的OC.zip还是release页面的呢?

**Comment by Rincaron** [comment]
release

**Comment by Rincaron** [comment]
![image](https://user-images.githubusercontent.com/72061002/116574991-d2871000-a940-11eb-93d9-c0f8690d2755.jpeg)
安装好了，感谢帮助！

**Comment by PurestAsh** [comment]
有什么不能用的硬件记得反馈哦!

**Comment by Rincaron** [comment]
触摸板不能用，那个补丁不会用😂

**Comment by Rincaron** [comment]
> 有什么不能用的硬件记得反馈哦!

触摸板不能用，那个补丁不会用😂

**Comment by PurestAsh** [comment]
现在这种方式是对我自己的dsdt.aml打补丁，也就是说acpi文件夹下面的dsdt.aml是来自于我机器的。尽管相同型号的机器，但是他们的dsdt某些细节可能也不尽相同，这可能是导致触摸板不可用的原因，这个我很难去解决。

除非
第一种：你们提取出自己机器原生的dsdt文件，然后对它打补丁，最后替换我的dsdt.aml，这样就能完美黑苹果，但是这样的话就要学习一点东西了，请看open core install guide acpi篇。

第二种：寻找热补丁的EFI(几乎很少)

第三种：再等等🤣我后期会考虑采用热补丁的方式实现
