### ISSUE TITLE
Hi，和up主一样的机型 触摸板还是无效 

### ISSUE THREAD

**Issue by echo9z** [threewater2/hackintosh#3]
SSDT 是有_SB.PCI0.I2C1.ETPD 与 INT3443  相关信息的，up主如何解决的呢？

**Comment by PurestAsh** [comment]
现在这种方式是对我自己的dsdt.aml打补丁，也就是说acpi文件夹下面的dsdt.aml是来自于我机器的。尽管相同型号的机器，但是他们的dsdt某些细节可能也不尽相同，这可能是导致触摸板不可用的原因，这个我很难去解决。

除非
第一种：你们提取出自己机器原生的dsdt文件，然后对它打补丁，最后替换我的dsdt.aml，这样就能完美黑苹果，但是这样的话就要学习一点东西了，请看open core install guide acpi篇。

第二种：寻找热补丁的EFI(几乎很少)

第三种：再等等🤣我后期会考虑采用热补丁的方式实现
